Update publish-action.yml

diff --git a/.github/workflows/publish-action.yml b/.github/workflows/publish-action.yml
--- a/.github/workflows/publish-action.yml
+++ b/.github/workflows/publish-action.yml
@@ -19,21 +19,21 @@ jobs:
           FULL_TAG: ${{ github.event.release.tag_name }}
         run:
           
-          if ! [[ "$FULL_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "::error::Invalid tag format (expected vX.Y.Z) !"
-            exit 1
+          if ! [[ "$FULL_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then \
+            echo "::error::Invalid tag format (expected vX.Y.Z) !"; \
+            exit 1; \
           fi;
 
           MINOR_TAG=`echo $FULL_TAG | cut -d '.' -f 1-2`;
-          if ! [[ "$MINOR_TAG" =~ ^v[0-9]+\.[0-9]+$ ]]; then
-            echo "::error::Invalid minor tag format (expected vX.Y) !"
-            exit 2
+          if ! [[ "$MINOR_TAG" =~ ^v[0-9]+\.[0-9]+$ ]]; then \
+            echo "::error::Invalid minor tag format (expected vX.Y) !"; \
+            exit 2; \
           fi;
 
           MAJOR_TAG=`echo $FULL_TAG | cut -d '.' -f 1`;
-          if ! [[ "$MINOR_TAG" =~ ^v[0-9]+\.[0-9]+$ ]]; then
-            echo "::error::Invalid major tag format (expected vX) !"
-            exit 3
+          if ! [[ "$MINOR_TAG" =~ ^v[0-9]+\.[0-9]+$ ]]; then \
+            echo "::error::Invalid major tag format (expected vX) !"; \
+            exit 3; \
           fi;
           
           git tag -f $MINOR_TAG && \
